### ISSUE TITLE
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Invalid regexp: "Trailing backslash"" on command post-command

### ISSUE THREAD

**Issue by Blade6570** [jcs-elpa/company-fuzzy#10]
Backtrace:
`Debugger entered--Lisp error: (invalid-regexp "Trailing backslash")
  string-match(#("\\" 0 1 (fontified t org-category "bug")) #(" \\C-ch <dabbrev-code>           1 " 0 1 (face (company-tooltip-selection company-tooltip-selection company-tooltip) mouse-face (company-tooltip-mouse)) 1 2 (face (company-tooltip-selection company-tooltip-common-selection company-tooltip-selection company-tooltip) mouse-face (company-tooltip-mouse)) 2 6 (face (company-tooltip-selection company-tooltip-selection company-tooltip) mouse-face (company-tooltip-mouse)) 6 21 (face (company-tooltip-annotation-selection company-tooltip-selection company-tooltip) mouse-face (company-tooltip-mouse)) 21 34 (face (company-tooltip-selection company-tooltip) mouse-face (company-tooltip-mouse))) nil)
  company-fuzzy--company-fill-propertize(#f(compiled-function (value annotation width selected left right) #<bytecode 0x1561d47cbde9>) "\\C-ch" " <dabbrev-code>" 30 t " " " 1 ")
  apply(company-fuzzy--company-fill-propertize #f(compiled-function (value annotation width selected left right) #<bytecode 0x1561d47cbde9>) ("\\C-ch" " <dabbrev-code>" 30 t " " " 1 "))
  company-fill-propertize("\\C-ch" " <dabbrev-code>" 30 t " " " 1 ")
  company--create-lines(0 10)
  company-pseudo-tooltip-show(2 2 0)
  company-pseudo-tooltip-show-at-point(16 1)
  company-pseudo-tooltip-frontend(post-command)
  company-pseudo-tooltip-unless-just-one-frontend(post-command)
  company-call-frontends(post-command)
  company-post-command()
  company-idle-begin(#<buffer bug.org> #<window 3 on bug.org> 158 16)
  apply(company-idle-begin (#<buffer bug.org> #<window 3 on bug.org> 158 16))
  timer-event-handler([t 24417 49290 773636 nil company-idle-begin (#<buffer bug.org> #<window 3 on bug.org> 158 16) nil 162000])
` 

I used the `company-fuzzy-mode` on any org file. If I start typing with `\` then it throws this error. 

**### My company setup:** 

_(use-package company
    :ensure t
    :config
    (setq company-minimum-prefix-length 1
	  ;; company delay until suggestions are shown
	  ;;company-idle-delay 0.1
          company-tooltip-align-annotations t
	  company-idle-delay 0
	  ;; weight by frequency
	  company-transformers '(company-sort-by-occurrence))
    (global-set-key (kbd "C-<tab>") 'company-manual-begin)
    (define-key company-active-map (kbd "C-n") 'company-select-next)
    (define-key company-active-map (kbd "C-p") 'company-select-previous)
    ;;(define-key company-active-map (kbd "TAB") 'company-complete-selection)
    ;;(define-key company-active-map (kbd "<tab>") 'company-complete-selection)
    (define-key company-active-map (kbd "RET") 'company-complete-common)
    ;;(define-key company-active-map (kbd "<return>") nil)
    ;;(define-key company-active-map (kbd "RET") nil)
    (global-company-mode)
    )_

**Comment by jcs090218** [comment]
I can reproduce this bug. Thanks for the report!

I have fixed with commit, see e01f7d386a21c96b8b081b6f45930540061fcb65. (for now)

**Comment by Blade6570** [comment]
Hi, 
based on the commit mentioned above, I have a similar way of fixing this issue. My idea is to first check whether the regexp is a valid regexp or not. If not then make it a string and show the match.

 (defun legal-regex-p (str)
  "Return t if STR is valid regular expression."
  (condition-case nil
      (progn
        (string-match-p str "")
        t)
    (invalid-regexp nil)))`

(defun company-fuzzy--string-match-p (regexp string &optional start)
  "Safe way to execute function 'string-match-p'.
See function 'string-match-p' for arguments REGEXP, STRING, and START."
  (if (legal-regex-p regexp)
      (string-match-p regexp string start)
      (string-match-p (regexp-quote regexp) string start)))

**Comment by Blade6570** [comment]
Now I see on the *master* brach you have kind of similar fix.  Anyway thanks.

**Comment by jcs090218** [comment]
Yeah, sorry for not mentioning it! The fix should appear in the latest version!

Close this issue now! Feel free to reopen this if this doesn't seems correct. 👍
