### ISSUE TITLE
Company-complete doesn't complete when inside of string

### ISSUE THREAD

**Issue by TrunovS** [jcs-elpa/company-fuzzy#11]
Found strange behaviour when trying to complete inside string with `global-company-fuzzy-mode` turned-on. 
Open scratch buffer and start new string with `"` `"buf<-complete here"`

My company backends config quite simple `(company-files company-yasnippet company-dabbrev)`

Is there some kind of workaround or smth?

**Comment by jcs090218** [comment]
This issue can be reproduce!

This issue should be fixed by this commit, 2dc7ccab0f4f059e60a0832f26ea2bf3625990d4. Can you try with the latest version? Thanks! 😄

**Comment by TrunovS** [comment]
> This issue can be reproduce!
> 
> This issue should be fixed by this commit, [2dc7cca](https://github.com/jcs-elpa/company-fuzzy/commit/2dc7ccab0f4f059e60a0832f26ea2bf3625990d4). Can you try with the latest version? Thanks! 😄

Works brilliantly!) Thanks!)
