### ISSUE TITLE
enabling company-fyzzy-mode disables semantic completion with eglot

### ISSUE THREAD

**Issue by andreyorst** [jcs-elpa/company-fuzzy#2]
Hi, I'm interested in fuzzy completions with company, and your package seems to be great. However I have several problems with it.

In particular, I use [eglot](https://github.com/joaotavora/eglot) a.k.a. Emacs polyglot, an [LSP](https://langserver.org/) client. Without `company-fyzzy-mode` after I type `ap->` I can see these semantic completions provided by `clangd` language server:
![Screenshot from 2019-10-12 11-09-12](https://user-images.githubusercontent.com/19470159/66697700-c5fc8180-ece0-11e9-8af5-f8728a8d6b97.png)

When `company-fuzzy-mode` is enabled, there's no completions in that case.

When trying to complete manually with `company-complete` I get this message:

    Company: backend company-fuzzy-all-other-backends error "Wrong type argument: stringp, nil" with args (candidates )

**Comment by jcs090218** [comment]
Hi, Unfortunately I never used eglot. What I could guess is because eglot company backend gives different format than just the string. Meaning this could be the mystery to me and this plugin because I have not dig deep enough on how each company backend is processed.

**Comment by jcs090218** [comment]
I will try and test out eglot’a company backend and hopefully I could find out something that could possibly resolved this issue.

**Comment by andreyorst** [comment]
eglot doesn't have company it's own backend. It uses `capf` and works with company through `company-capf`

**Comment by jcs090218** [comment]
Oh, okay. At the time I created this plugin and I do encountered company backend's `clangd` doesn't returns the `list of string`; instead it return a `plist` which I haven't really look into it yet. I think I will just have to solve the `plist` in order to make this plugin works with `clangd` backend.

**Comment by jcs090218** [comment]
Just a quick update for this thread!

I have tried LSP mode and they already have fuzzy completion with `company-lsp`. Yet I don't know about `eglot`, but in LSP you probably don't want to enable this package and better to keep it disabled. I may have plan to make this package compatible to `lsp` and `eglot` but currently I don't have a good solution for this issue/conflict.

**Comment by andreyorst** [comment]
`eglot` doesn't work with `company-lsp`, it only uses `capf`, and AFAIC `company-lsp` is deprecated in `lsp-mode`, and suggest using `capf` as well.

**Comment by jcs090218** [comment]
> eglot doesn't work with company-lsp, it only uses capf, and AFAIC company-lsp is deprecated in lsp-mode, and suggest using capf as well.

Oh, yes. You are correct! I just notice this by now. 😲 I guess I will try eglot and see if I can fix this. 😄 Currently this package work well with `lsp`. Thanks for the information!

**Comment by andreyorst** [comment]
I've also switched to lsp-mode some time ago, so this bug is for feature-completiness sake. I mean it's not high priority for me

**Comment by jcs090218** [comment]
Good to hear! Since this is the known issue, and just in case some else might have the same issue I will keep this issue opened. Thanks! :)

**Comment by zhenhua-wang** [comment]
Eglot would force `company-backends` to be "compang-capt" after it has managed the current buffer. I can get completion by adding the following hook
`(add-hook 'eglot-managed-mode-hook (lambda () (setq-local company-backends '(company-fuzzy-all-other-backends))))`

**Comment by jcs090218** [comment]
Closing this now since this isn't `company-fuzzy`'s issue. People should probably report it to eglot!

**Comment by jcs090218** [comment]
Now, `company-fuzzy` should be able to handle eglot nicely by default, see 3c8c960b4e5341f6806cf43aa794c0798051222d.
