### ISSUE TITLE
Order is not respected when variable starts with @ (ruby-mode)

### ISSUE THREAD

**Issue by otavioschwanck** [jcs-elpa/company-fuzzy#22]
Here an example:
![image](https://user-images.githubusercontent.com/9551316/147868938-4725b490-70f9-4e4d-a4c2-1bf4ad77fcc5.png)

value on company-fuzzy--backends:

(company-capf company-dabbrev-code company-ruby-backend company-rspec-backend)

**Comment by jcs090218** [comment]
Are you using `lsp-mode`? Try tweak the variable `company-fuzzy-passthrough-backends`.

Full usage, see [here](https://github.com/jcs-emacs/jcs-emacs/blob/40321a314bfd83d6bbab279d3f1206ca56741fdc/.emacs.jcs/func/jcs-lsp.el#L10-L20).

Initial PR, #19.

For documentation, see [company-fuzzy#-excluding](https://github.com/jcs-elpa/company-fuzzy#-excluding).

**Comment by jcs090218** [comment]
Long answer is: at symbol `@` isn't be detected as a prefix. See function `company-fuzzy--get-prefix`.

https://github.com/jcs-elpa/company-fuzzy/blob/ca52f1bf0a2ad927d629274f648726769ce770de/company-fuzzy.el#L669-L673

You can modify the syntax entry by doing the following:

```el
(add-hook 'ruby-mode-hook (lambda () (modify-syntax-entry ?@ "w"))
```

---

Hope the above information helps!

**Comment by otavioschwanck** [comment]
Hi @jcs090218 , thanks for you answer.

Setting `company-fuzzy-passthrough-backends` to '(company-capf) doesnt work, same problem.

Adding the hook (add-hook 'ruby-mode-hook (lambda () (modify-syntax-entry ?@ "w"))) did the trick <3

Thanks for your attention, i love the fuzzy on company <3
