### ISSUE TITLE
Link to configuration in the readme doesn't work

### ISSUE THREAD

**Issue by m-cat** [jcs-elpa/company-fuzzy#24]
https://github.com/jcs-emacs/jcs-emacs/blob/master/.emacs.jcs/jcs-plugin.el results in a 404.

**Comment by jcs090218** [comment]
Oops, new link https://github.com/jcs-emacs/jcs-emacs/blob/21a886dea0da6ff6459f4e853f1637bd3681a4ae/lisp/jcs-plugin.el#L160-L166.

Fixed in da4cb82d5840abd7298da4f1af1aef48ff6c0dc2.
