### ISSUE TITLE
Appropriate hook to enable after changing backends

### ISSUE THREAD

**Issue by BlueDrink9** [jcs-elpa/company-fuzzy#28]
This is more a help request, but I feel comfortable making it because it should have general appeal.

I have `(set-company-backend! 'prog-mode [backends])` in my config. It's a Doom function that adds to backends when changing major modes.

I have tried enabling company-fuzzy with company-mode-hook, the major mode change hook, and even advising set-company-backends.

I can get a final result where the backends seem to be set correctly for fuzzy, but no autocompletion occurs. Disabling then reenabling company-mode doesn't fix it, but doing so for company-fuzzy does.

On startup, when I expect autocompletion and none occurs, `company-backends` is `((:separate company-capf company-yasnippet) company-fuzzy-all-other-backends)`. After restarting, it is only `(company-fuzzy-all-other-backends)`

Any suggestions for how best to enable fuzzy?

**Comment by jcs090218** [comment]
I don't think there is an official hook to enable `company-fuzzy` since the user should able to customize the `company-backends` at any time. But the best solution, for now, is the following functions,

```elisp
(company-fuzzy-backend-add    'company-capf)
(company-fuzzy-backend-remove 'company-yasnippets)
```

For more information, see https://github.com/jcs-elpa/company-fuzzy#-what-if-i-want-to-add-backends-to-specific-major-mode

Example (my config): https://github.com/jcs-emacs/jcs-emacs/search?q=company-fuzzy-backend-add

Hope these info helps! :)

**Comment by BlueDrink9** [comment]
I saw those functions for adding/removing fuzzy backends, but I already have the backends I need. I think my issue is that when I do `(add-hook! company-mode-hook company-fuzzy-mode)`, I end up with `((:separate company-capf company-yasnippet) company-fuzzy-all-other-backends)` for `(company-backends)` rather than just `(company-fuzzy-all-other-backends)`. When it  is `((:separate company-capf company-yasnippet) company-fuzzy-all-other-backends)`, company does not seem to complete anything.

Would you expect company-fuzzy to work with `company-backends` set to `((:separate company-capf company-yasnippet) company-fuzzy-all-other-backends)`?

**Comment by BlueDrink9** [comment]
Ended up fixing it. I found that doom was also setting backends a second time for lsp-mode, which was activated in the mode I was testing this in. Added the advice to that to set fuzzy, and I'm all good now!
