### ISSUE TITLE
Yasnippet offers candidates for every prefix

### ISSUE THREAD

**Issue by BlueDrink9** [jcs-elpa/company-fuzzy#29]
I have added it to `company-fuzzy-history-backends` as suggested, but I still get every available snippet pop up as an option for every key that I type, regardless of prefix.

Is there any way to have it only fuzzy match the snippet description instead?

**Comment by jcs090218** [comment]
I think this is a known issue but I couldn't figure out the way to trigger this bug. Can you give me the steps to reproduce this bug? Even better with `emacs -Q`!

Thanks you! ❤️

**Comment by BlueDrink9** [comment]
Ah, the request we always expect and never hope to see. Yup, I'll try. Is a doom emacs minimal ok?

**Comment by jcs090218** [comment]
After reading the source [company-yasnippet](https://github.com/company-mode/company-mode/blob/master/company-yasnippet.el), I have better the understanding to the implementation. Can you test out the branch #30?

It should make `company-yasnippet` work like other company backends (regular)!

**Comment by jcs090218** [comment]
I think #30 should resolve this issue. Try update this package to the latest version, I'm going to close this issue now.

Feel free to reopen this issue if it hasn't been resolved! Thanks! ❤️
