### ISSUE TITLE
Using company-fuzzy with merged backends

### ISSUE THREAD

**Issue by jojojames** [jcs-elpa/company-fuzzy#3]
I have backends defined this way in company-mode.

```
((company-bbdb :with company-yasnippet company-dabbrev-code)
 (company-semantic :with company-yasnippet company-dabbrev-code)
 (company-cmake :with company-yasnippet company-dabbrev-code)
 (company-capf :with company-yasnippet company-dabbrev-code)
 (company-files :with company-yasnippet company-dabbrev-code)
 (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-oddmuse :with company-yasnippet company-dabbrev-code)
 (company-dabbrev :with company-yasnippet company-dabbrev-code))
```

It looks like when using these backends with company-fuzzy, company-fuzzy doesn't know what to do with the :with keyword and chokes upon trying to complete. e.g. Nothing shows/completes with :with.

Not sure what the best way to handle it in company-fuzzy since company-fuzzy tries to do a completion on all backends. Maybe an extract and pull out the :with backends into the same list.

e.g.

```
(company-capf :with company-yasnippet company-dabbrev-code)
(company-files :with company-yasnippet company-dabbrev-code)
```

becomes

```
(company-capf company-files company-yasnippet company-dabbrev-code)
```

internally.

Merge function I use:

```
  (defun merge-backend-with-company-backends (backend-to-merge)
    "Merges a backend with every backend in company-backends.
BACKEND-TO_MERGE will only be merged if it's not already in the current backend.

Merging `company-yasnippet' to `company-capf' will yield
'\(company-capf :with company-yasnippet\)."
    (setq company-backends
          (mapcar (lambda (backend)
                    (cond
                     ((and (listp backend)
                           (member backend-to-merge backend))
                      backend)
                     (:else
                      (append (if (consp backend)
                                  backend
                                (list backend))
                              (if (and (listp backend)
                                       (member :with backend))
                                  `(,backend-to-merge)
                                `(:with ,backend-to-merge))))))
                  company-backends)))
```

Thanks for the interesting package!

**Comment by jcs090218** [comment]
> It looks like when using these backends with company-fuzzy, company-fuzzy doesn't know what to do with the :with keyword and chokes upon trying to complete. e.g. Nothing shows/completes with :with.

You are correct, I don't know how to handle company backend with the `:with` keyword. But now I think I do! :D 

> Not sure what the best way to handle it in company-fuzzy since company-fuzzy tries to do a completion on all backends. Maybe an extract and pull out the :with backends into the same list.

I think this could be good enough since this doesn't really hurt in the run time instead is in the initialize time.

**Comment by jcs090218** [comment]
I have implemented this the latest version using `company-fuzzy--normalize-backend-list` function. Close this now! :)

**Comment by jojojames** [comment]
Would be super helpful (for me anyways :D) for some documentation around this so when I find the time, I'll be able to make a swift transition. Thanks for implementing this @jcs090218 !
